server:
  port: 9303
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: gateway-server
  zipkin:
    base-url: http://localhost:9301
  sleuth:
    sampler:
      percentage: 1.0
  zuul:
    routes:
      api:
        path: /client/**
        serviceId: zipkin-client