server:
  port: 9301
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: zipkin-server
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  datasource:
    url: jdbc:mysql://localhost:3306/spring-cloud-zipkin?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
zipkin:
  storage:
    type: mysql