spring:
  application:
    name: service-hi

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-oauth2?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: 9091

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/uaa/users/current
    client:
      clientId: service-hi
      clientSecret: 123456
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials,password
      scope: server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/