eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:  security:    enabled: false
server:  port: 9093
  
spring:
  application:
    name: admin-client-brother