eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:  security:    enabled: false
server:  port: 9094

spring:
  application:
    name: turbine-server
    
turbine:
  aggregator:
    clusterConfig: 
      default
  appConfig: client-server,client-brother-server
  clusterNameExpression: new String("default")
  