server:
  port: 8080
spring:
  cloud:
    config:
      server:
        native:           search-locations: classpath:/conf
  profiles:    active: native
  application:    name: config-server