server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:          uri: https://github.com/TonyStark888/cloudStd
          search-paths: sample_v1.1
      label: master
  application:    name: config-server
     #添加rabbitmq信息，用于发送配置信息刷新的消息通知
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
#注册Eureka的配置项
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true