server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:          uri: https://github.com/TonyStark888/cloudStd
          search-paths: sample_v1.1
      label: master
  application:    name: config-server