eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management:  security:    enabled: false
server:  port: 9091
logging:  file: "logs/boot-admin-sample.log"

spring:
  application:
    name: admin-server
  boot:
     admin:
        routes:
          endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hysstrix.stream                                                                                                                                                                                                                                                           