eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
management: 
  security: 
    enabled: false
server:  port: 9302
spring:
  application:
    name: zipkin-client
  zipkin:
    base-url: http://localhost:9301
  sleuth:
    sampler:
      percentage: 1.0